--- #YAML:1.0
name:                DNS-ZoneParse
version:             0.96
abstract:            Parse and manipulate DNS Zone Files.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Storable:                      0.407
    Test::More:                    0.31
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Simon Flack (perl@simonflack.com)
