--- #YAML:1.0
name:               DNS-ZoneParse
version:            1.10
abstract:           Parse and manipulate DNS Zone Files.
author:
    - Simon Flack (perl@simonflack.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Storable:    0.407
    Test::More:  0.31
resources:
    repository:  http://github.com/mschilli/dns-zoneparse-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
